"""Created table Lego 2

Revision ID: 616b5e1f2d6b
Revises: 29bba2747f27
Create Date: 2024-01-14 22:59:42.103855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616b5e1f2d6b'
down_revision: Union[str, None] = '29bba2747f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('listingImages', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('ageRange', sa.String(), nullable=False),
    sa.Column('pieceCount', sa.Integer(), nullable=False),
    sa.Column('formattedAmount', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lego')
    # ### end Alembic commands ###
