"""Added column product

Revision ID: d17771f2dded
Revises: 564e51db213b
Create Date: 2024-02-04 20:13:59.744154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17771f2dded'
down_revision: Union[str, None] = '564e51db213b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.JSON(), nullable=True))
    op.drop_column('cart', 'formattedAmount')
    op.drop_column('cart', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('formattedAmount', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###
